### DISCUSSION TITLE
Adding ssh key to --on?

### DISCUSSION THREAD

**Discussion by commandodev** [juspay/omnix#426] [Q&A]
I've got this:

```
 - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra-nix-config: |
            builders = ssh://${{ vars.NIX_BUILDER }} x86_64-linux ${{ env.SSH_LOCATION }} 0 0
            builders-use-substitutes = true
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Install Cachix and Omnix
        run: "nix profile install --accept-flake-config github:juspay/omnix nixpkgs#cachix"
      - name: Authenticate Cachix
        run: "cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }} && cachix use ${{ vars.CACHE_NAME }}"
      - name: Build all flake outputs and push to Cachix
        run: "om ci run --on ssh://${{ vars.NIX_BUILDER }} | cachix push ${{ vars.CACHE_NAME }}"
```

But my remote builder need an SSH key. How do I add that?
