### ISSUE TITLE
`om health`(`nix-version`): Add `vulnerableVersions`

### ISSUE THREAD

**Issue by shivaraj-bh** [juspay/omnix#386]
For times when only specific versions of `nix` are problematic

**Comment by srid** [comment]
So this would be `nix-version.vulnerable = [ ... ]`?

We should also update the "Fix" suggestion here, because that doesn't seem accurate if you are on home-manager, wherein one would just need to update nixpkgs and activate.

<img width="503" alt="Image" src="https://github.com/user-attachments/assets/4a120abb-cc89-4286-8d9d-788ad537ff2e" />

**Comment by shivaraj-bh** [comment]
```yaml
nix-version:
  supported:
    - ">2.24.3"
    - "<2.24.3, >2.8"
```

API proposed by @srid over slack
